### PR TITLE
zypper: be more careful when installing systemd-coredump

### PR DESCRIPTION
**Pull request by smithfarm**
provision.sh: include zypper repo setup in --no-provision
    
    Recently a --no-provision feature was added to provide a way to quickly
    bring up a VM. But in order for that feature to be useful, the VM should
    have the same repos as in a full deployment.
    
    Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

    zypper: be more careful when installing systemd-coredump
    
    Due to the way Kiwi builds SLE Vagrant Boxes, the versions of packages
    pre-installed in the Vagrant Box may be newer than the versions of the same
    packages in the "channels" (i.e., in the zypper repos that are added after the
    VMs start).
    
    Work around this by force-installing systemd, udev, etc. from the repos.
    
    This has the drawback of putting the system into a state where "zypper ps -s"
    reports that it needs a reboot.
    
    Fixes: https://github.com/SUSE/sesdev/issues/575
    Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

    zypper: add "lsof" to basic set of packages to install
    
    The "lsof" package is required for "zypper ps -s" to work.
    Apparently, it is not pre-installed in at least one of the Vagrant Boxes that
    we use.
    
    Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

    provision.sh: inform user if reboot is needed
    
    Run "zypper ps -s" at the very end of the provisioning script.
    
    Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

    qa: add assert_reboot_not_needed test
    
    As part of qa-test, run "zypper ps -s" on all nodes and evaluate the output.
    
    If any node is in need of reboot, abort the test and instruct the user that
    it would be better if the cluster were rebooted before running qa-test.
    
    Since rebooting the cluster before running qa-test would have to be done
    manually, failure of this test currently only results in a "soft failure"
    (warning), not a hard failure.

        Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

Fixes: https://github.com/SUSE/sesdev/issues/575

### CODE REVIEW

**Comment by smithfarm** [comment]
@p-se In my environment, this PR fixes #575 at least for `sesdev create ses6 --single-node`. What do you think?

**Review by p-se — APPROVED** [review]
works (even for `sesdev create ses6` (4 node) cluster)

**Comment by smithfarm** [comment]
My only reservation is that, since this introduces the possibility that system processes will end up using deleted files, maybe the user should be made aware of this via some warning message.

**Comment by smithfarm** [comment]
`contrib/standalone.sh` is a little rough these days (due to a small collection of issues unrelated to this PR), but I'm satisfied that this PR is now working as expected.

**Pull request merged**
