### PR TITLE
adapted install from source guide

### PR DESCRIPTION
**Pull request by capri1989**
Signed-off-by: Kai Wagner <kwagner@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
I don't know - this repeats information from further up in the document, and it doesn't seem to take into account the possibility that the user might be using a remote libvirtd?

**Comment by smithfarm** [comment]
I looked again, and I think if you start reading here:

https://github.com/SUSE/sesdev#installation

and read until the end, everything should be fine. The problem happens if you start reading here:

https://github.com/SUSE/sesdev#install-sesdev-from-source

Correct? In that case, would it be sufficient to add a sentence to "Install sesdev from source" saying something like:

"The instructions in this section assume that the user has already completed all the previous instructions in this 'Installation' chapter."

?

**Comment by capri1989** [comment]
> I looked again, and I think if you start reading here:
> 
> https://github.com/SUSE/sesdev#installation
> 
> and read until the end, everything should be fine. The problem happens if you start reading here:
> 
> https://github.com/SUSE/sesdev#install-sesdev-from-source
> 
> Correct? In that case, would it be sufficient to add a sentence at the beginning of the "Install sesdev from source" section - something like:
> 
> "The instructions in this section assume that the user has already completed all the previous instructions in this 'Installation' chapter."
> 
> ?

No, as packages are missing that are needed for the source install and usage such like gcc, python-devel etc etc.

Also vagrant libvirt is documented underneath install from packages and not source or in general, so we either have to move it somewhere else or mention it here again

**Comment by smithfarm** [comment]
I have opened  #94 to address the concerns raised here. Feel free to reopen if you don't like that.

**Pull request closed without merging**
