### PR TITLE
Jenkinsfile: Use configured image

### PR DESCRIPTION
**Pull request by toabctl**
There is a Jenkins parameter for using a specific image. That
parameter is currently not used.

Fixes: #152

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Just to echo what I've written elsewhere...

There are currently two "versions" that use `--image-path`: octopus and ses7.

In order for the test to be valid, the version of cephadm and the version of ceph inside the container should be the same, and we have a QA test to enforce this.

Each "version" (octopus and ses7) has:

* a default set of repos for installing cephadm
* a default container image path

The defaults for these two are chosen to maximize the chances that

* a relevant (recent) version of cephadm+container image will be tested
* the version numbers will match

For these reasons, I don't think it makes sense for the Jenkins test to specify `--image-path` without also specifying `--repo` (these two go together).

**Comment by smithfarm** [comment]
`The CEPH_SALT_FROM_GIT_MASTER is the default and it currently doesn't
make sense to have that configurable. So drop it.`

This is not true. AFAIK we need to always pass `--ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master` explicitly. Otherwise we will get whichever version of ceph-salt that happens to be in the repos.

**Comment by toabctl** [comment]
@smithfarm updated the commit msg.

**Comment by smithfarm** [comment]
Thanks, @toabctl

**Pull request merged**
