### PR TITLE
contrib/upgrade-demo-ses6-to-ses7.sh: add upgrade demo script

### PR DESCRIPTION
**Pull request by smithfarm**
This script demonstrates how to create an upgradeable SES6 cluster
and then upgrade it to SES7.

Fixes: https://github.com/SUSE/sesdev/issues/533
Signed-off-by: Nathan Cutler <ncutler@suse.com>

---

NOTE: To run successfully, this PR needs the following PRs:

- [x] https://github.com/SUSE/sesdev/pull/530 (merged)
- [x] https://github.com/SUSE/sesdev/pull/531 (merged)
- [x] https://github.com/SUSE/sesdev/pull/532 (merged)
- [x] https://github.com/SUSE/sesdev/pull/538 (merged)
- [x] https://github.com/SUSE/sesdev/pull/539 (merged)
- [x] https://github.com/SUSE/sesdev/pull/540 (merged)

### CODE REVIEW

**Comment by smithfarm** [comment]
@tserong I haven't run this script yet, but I followed all the steps and the last command returned an error:

```
(venv) smithfarm@vanguard1:~/sesdev> sesdev ssh ses6 master "bash -x -c 'ceph-salt apply'"
+ ceph-salt apply
Syncing minions with the master...
Failed to check if ceph is configured on minion 'master.ses6.test'
WARNING: SSH interactive session finished with ret=1
```

**Comment by tserong** [comment]
Curious. I'll give it a shot here and see if I can reproduce.

**Comment by smithfarm** [comment]
Thanks @tserong 

I just merged #530, #531 and #532 - so it should be possible to run this script directly on an installation of sesdev master, without fiddling with patches.

**Comment by tserong** [comment]
Excellent, thanks. Will let you know how I go.

**Comment by smithfarm** [comment]
@tserong I think I found the issue. After `zypper in ceph-salt` we have to do:

```
systemctl restart salt-master.service
salt \* saltutil.sync_all
```

I updated the Confluence page and the script - just now - so this is reflected. I also fixed a stupid typo in the script.

**Comment by smithfarm** [comment]
Now the problem appears to be that this line sometimes fails:

```
sesdev ssh ses6-to-ses7 master salt node1.ses6.test state.apply ceph.upgrade.ses7.adopt
```

When this happens (the `salt` command appears to do nothing), the cluster gets stuck and it's no longer possible to run `ceph -s`.

I think it happens because, for whatever reason, the Salt cluster has not recovered from the reboot. I'll add a `test.ping` check after each reboot.

**Comment by smithfarm** [comment]
Good news. With this version, I got all the way to:

```
+ ceph-salt apply
Syncing minions with the master...
No time server subnet specified in config
```

We will need up to update the Confluence page for this, I guess.

**Comment by smithfarm** [comment]
>  so maybe this is something that could be fixed in DeepSea?

Upon closer examination, we found that this problem can be avoided by having DeepSea set `/time_server` to `disabled` in the config export. This also has the advantage of ensuring that `ceph-salt` does not munge the SES6 cluster's (presumably already existing and functioning) time sync setup.

**Comment by smithfarm** [comment]
I believe this script is working now. If you were thinking about giving it a try, please don't hold back :-)

**Comment by smithfarm** [comment]
It occurred to me that creating the SES6 cluster should be optional. I'll add a commit later to make the script take an optional argument (the dep_id of an existing cluster to be upgraded). If the argument is given, it will upgrade that cluster. If not given, it will create the cluster, first.

**Pull request merged**
