### PR TITLE
qa: add iscsi test

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by kshtsk** [comment]
the test is failing on jenkins

**Comment by trociny** [comment]
> the test is failing on jenkins

I believe I have fixed the issue. Will it rerun on jenkins automatically after I have pushed the update?

**Comment by kshtsk** [comment]
> > the test is failing on jenkins
> 
> I believe I have fixed the issue. Will it rerun on jenkins automatically after I have pushed the update?

Just do it and see

**Comment by trociny** [comment]
jenkins failed but this time it does not look related

**Review by tserong — APPROVED** [review]

**Comment by tserong** [comment]
> jenkins failed but this time it does not look related

Yeah, looks like a missing admin keyring after deployment, which is unrelated, makes no sense, and I can't reproduce.

**Comment by tserong** [comment]
...and now having looked in more detail: #690 should fix that.

**Comment by tserong** [comment]
> But this is an example, why we shouldn't merge a PR without all tests passed.

Indeed.

**Pull request merged**
