### PR TITLE
Implement "sesdev box remove --all" feature

### PR DESCRIPTION
**Pull request by smithfarm**
We had a way to remove a single box, but no way to blow away all boxes
at once.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by LenzGr** [comment]
This seems to have broken the removal of a single box for me:
```
$ sesdev box list
List of all Vagrant Boxes installed in the system
-------------------------------------------------
leap-15.1
leap-15.2
sles-12-sp3
sles-15-sp1
sles-15-sp2
$ sesdev box remove leap-15.1
Traceback (most recent call last):
  File "/home/lenz/work/sesdev/venv/bin/sesdev", line 33, in <module>
    sys.exit(load_entry_point('sesdev', 'console_scripts', 'sesdev')())
  File "/home/lenz/work/sesdev/sesdev/__init__.py", line 40, in sesdev_main
    cli(prog_name='sesdev')
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lenz/work/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lenz/work/sesdev/sesdev/__init__.py", line 342, in remove_box
    settings_dict = _gen_box_settings_dict(**kwargs)
TypeError: _gen_box_settings_dict() got an unexpected keyword argument 'all'
```

**Comment by smithfarm** [comment]
@LenzGr Sorry, I pinged you for review before the PR was actually ready. Can you try it again?

**Comment by LenzGr** [comment]
> Can you try it again?

Just tried, and `sesdev box remove --all` now works as expected. However, removing a single box previously asked for confirmation, this is no longer the case. Before:
```
$ sesdev box remove leap-15.1
Are you sure you want to remove the Vagrant Box? [y/N]: n
```
Now it just proceeds:
```
$ sesdev box remove leap-15.1
Attempting to remove Vagrant Box ->leap-15.1<- ...
```

This also applies to the `--all` option:

```
$ sesdev box list
List of all Vagrant Boxes installed in the system
-------------------------------------------------
leap-15.2
sles-12-sp3
sles-15-sp1
sles-15-sp2
$ sesdev box remove --all
Attempting to remove Vagrant Box ->leap-15.2<- ...
Attempting to remove Vagrant Box ->sles-12-sp3<- ...
Attempting to remove Vagrant Box ->sles-15-sp1<- ...
Attempting to remove Vagrant Box ->sles-15-sp2<- ...
WARNING: The following deployment is already using Vagrant Box ->sles-15-sp2<-:
WARNING:         ses7

WARNING: It must be destroyed first!
3 Vagrant Boxes were removed
WARNING: sesdev tried to remove 4 Vagrant Box(es), but problems were encountered.
Use "sesdev box list" to check current state
```
I think we should preserve the confirmation question before proceeding with the deletion of both a single and all boxes.

**Comment by LenzGr** [comment]
Now the removal of boxes does not seem to work at all anymore:

Before:
```
$ sesdev box remove sles-15-sp2
Attempting to remove Vagrant Box ->sles-15-sp2<- ...
WARNING: The following deployment is already using Vagrant Box ->sles-15-sp2<-:
WARNING:         ses7

WARNING: It must be destroyed first!
0 Vagrant Boxes were removed
WARNING: sesdev tried to remove 1 Vagrant Box(es), but problems were encountered.
Use "sesdev box list" to check current state
```

Now:
```
sesdev box remove sles-15-sp2
Aborted!
```

The same error occurs for unused boxes.

**Comment by smithfarm** [comment]
@LenzGr I really appreciate your help reviewing and testing this. Could you try it one more time?

**Comment by LenzGr** [comment]
> Could you try it one more time?

Just did so - looks good to me! Thank you.

**Review by LenzGr — APPROVED** [review]

**Pull request merged**
