### PR TITLE
podman container cannot be stopped due to AppArmor

### LINKED ISSUE #60: podman container cannot be stopped due to AppArmor
Octopus cluster, but likely also affects ses7, where the package also isn't installed.

```
node2:~ # podman ps 
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
019bb018c46c docker.io/prom/node-exporter:latest /bin/node_exporte... 3 minutes ago Up 3 minutes ago ceph-93c29e18-309f-11ea-83a2-52540028a9f3-node-exporter.ceph.com
23bd957645b8 docker.io/ceph/daemon-base:latest-master-devel /usr/bin/ceph-osd... 28 hours ago Up 28 hours ago ceph-93c29e18-309f-11ea-83a2-52540028a9f3-osd.4
f02f2155fe52 docker.io/ceph/daemon-base:latest-master-devel /usr/bin/ceph-osd... 28 hours ago Up 28 hours ago ceph-93c29e18-309f-11ea-83a2-52540028a9f3-osd.5
0251709461e1 docker.io/ceph/daemon-base:latest-master-devel /usr/bin/ceph-osd... 28 hours ago Up 28 hours ago ceph-93c29e18-309f-11ea-83a2-52540028a9f3-osd.6
09c9178b0506 docker.io/ceph/daemon-base:latest-master-devel /usr/bin/ceph-osd... 28 hours ago Up 28 hours ago ceph-93c29e18-309f-11ea-83a2-52540028a9f3-osd.7

node2:~ # podman stop ceph-93c29e18-309f-11ea-83a2-52540028a9f3-node-exporter.ceph.com
ERRO[0000] container_linux.go:389: signaling init process caused "permission denied" 
container_linux.go:389: signaling init process caused "permission denied"
Error: permission denied

node2:~ # aa-teardown 
Unloading AppArmor profiles 

node2:~ # podman stop ceph-93c29e18-309f-11ea-83a2-52540028a9f3-node-exporter.ceph.com
019bb018c46c78ebd2cb758ff7b13a1ca67a9546c6dc48ed13fbe9432edb6b8a

node2:~ # 

dmesg related output:

[101894.050966] audit: type=1400 audit(1578575016.796:3): apparmor="DENIED" operation="signal" profile="libpod-default-1.4.4" pid=19883 comm="podman" requested_mask="receive" denied_mask="receive" signal=exists peer="unconfined"
[101894.057036] audit: type=1400 audit(1578575016.800:4): apparmor="DENIED" operation="signal" profile="libpod-default-1.4.4" pid=19893 comm="runc" requested_mask="receive" denied_mask="receive" signal=term peer="unconfined"
[101894.058783] audit: type=1400 audit(1578575016.804:5): apparmor="DENIED" operation="signal" profile="libpod-default-1.4.4" pid=19883 comm="podman" requested_mask="receive" denied_mask="receive" signal=exists peer="unconfined"
```

### PR DESCRIPTION
**Pull request by p-se**
Closes #60

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
@p-se this kind of issue should be reported and fixed in the [ceph-bootstrap](https://github.com/SUSE/ceph-bootstrap) project. The current apparmor state of ceph-salt-formula is still doing almost nothing and we need to improve it. See https://github.com/SUSE/ceph-bootstrap/issues/12

**Comment by sebastian-philipp** [comment]
Maybe we should even make `cephadm` depend on `apparmor-profiles` for SUSE? cc @smithfarm ?

**Comment by smithfarm** [comment]
@p-se @sebastian-philipp Presumably this issue affects anyone who uses ceph-bootstrap to deploy a cluster, not just `sesdev`. If that's the case, would bugzilla be a better place to discuss this issue?

**Comment by smithfarm** [comment]
@sebastian-philipp My opinion on this is that there is nothing in cephadm that would require AppArmor to be installed in order to use it. It's up to the deployment tool that enables AppArmor (ceph-bootstrap in this case) to install the packages that are needed.

**Comment by p-se** [comment]
Closing in favor of a ceph-bootstrap implementation.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp My opinion on this is that there is nothing in cephadm that would require AppArmor to be installed in order to use it.

That's not completely true. `cephadm` depends on `podman`, which might depend on apparmor profiles.

**Comment by smithfarm** [comment]
My opinion that it's questionable to have a hard dependency on apparmor profiles in any package, because those profiles are not needed on systems that have AppArmor disabled. But that's just my personal opinion.

**Pull request closed without merging**
