### PR TITLE
ci: parametrize jcs repo

### PR DESCRIPTION
**Pull request by m-ildefons**
Add parameter for custom JCS repo to allow testing fixes to JCS before deploying to production

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
tests are failing

**Comment by m-ildefons** [comment]
See https://github.com/SUSE/sesdev/pull/675

**Comment by kshtsk** [comment]
needs to rebase

**Comment by kshtsk** [comment]
jenkins retest this

**Comment by kshtsk** [comment]
jenkins retest this

**Pull request merged**
