### PR TITLE
usability: redesign box remove dialogue

### PR DESCRIPTION
**Pull request by m-ildefons**
Rediesign box removal dialogue to first check for deployments using a
vagrant box and then ask the user for confirmation. This removes
confusion when a box being used by a deployment is beign removed.

fixes: #619
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

### CODE REVIEW

**Comment by tserong** [comment]
I've given this a quick test, and the logic seems right, but I've hit an odd error.

The first part works fine (although there's a typo -- need to `s/myst/must/`):

```
> sesdev box remove sles-15-sp2
You have asked to remove the following Vagrant Box
--------------------------------------------------
sles-15-sp2

WARNING: The following deployment is already using Vagrant Box >> sles-15-sp2 <<:
WARNING:         ses7-mini
WARNING: It myst be destroyed first!

0 Vagrant Boxes were removed
WARNING: sesdev tried to remove ['sles-15-sp2'] Vagrant Box(es), but problems were encountered.
Use "sesdev box list" to check current state
```

Now remove the deployment:

```
> sesdev destroy ses7-mini
Do you really want to destroy 1 cluster [Y/n]: y
Deployment ses7-mini destroyed!
```

Now try to remove the box:

```
You have asked to remove the following Vagrant Box
--------------------------------------------------
sles-15-sp2

Do you really want to remove box >> sles-15-sp2 << ? [Y/n]: y
Images matching Vagrant Box ->sles-15-sp2<-
===================================================
sles-15-sp2_vagrant_box_image_0_box.img
sles-15-sp2_vagrant_box_image_0.img

Traceback (most recent call last):
  File "/home/tserong/src/github/SUSE/sesdev/venv/bin/sesdev", line 33, in <module>
    sys.exit(load_entry_point('sesdev', 'console_scripts', 'sesdev')())
  File "/home/tserong/src/github/SUSE/sesdev/sesdev/__init__.py", line 45, in sesdev_main
    cli(prog_name='sesdev')
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tserong/src/github/SUSE/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tserong/src/github/SUSE/sesdev/sesdev/__init__.py", line 1046, in remove_box
    box_remove_handler(box_name, **kwargs)
  File "/home/tserong/src/github/SUSE/sesdev/sesdev/box.py", line 83, in box_remove_handler
    image_to_remove = box_obj.get_image_by_box(box_being_removed)
  File "/home/tserong/src/github/SUSE/sesdev/seslib/box.py", line 85, in get_image_by_box
    assert False, \
AssertionError: Too many matching images. Don't know which one to remove. This should not happen - please raise a bug!
```

`virsh vol-list` confirms that I do somehow seem to have two sles-15-sp2 vagrant box images:

```
> virsh vol-list default|grep sp2
 sles-15-sp2_vagrant_box_image_0.img                                                     /var/lib/libvirt/images/sles-15-sp2_vagrant_box_image_0.img
 sles-15-sp2_vagrant_box_image_0_box.img                                                 /var/lib/libvirt/images/sles-15-sp2_vagrant_box_image_0_box.img
```

**Comment by m-ildefons** [comment]
Does it work without this patch? I suppose the older image you have is an orphan from an earlier version of sesdev using a different naming style. If that is the case, the error should still appear, because the old dialogue didn't support this case either.

**Comment by tserong** [comment]
Aha! Yeah, it's still broken for me without this patch, so let's run with the old orphan assumption and ignore that complaint.

**Review by tserong — APPROVED** [review]
LGTM, but please s/myst/must/ :-)

**Pull request merged**
